#!/usr/bin/env bash

cd `dirname $0`

# Download data (only needs to be done once)
./download_data

# Execute a single experiment of each dataset
# - Note that the paper performs 10 experiments and takes the mean of their performance
./run_unsw_nb15
./run_ton_iot
./run_ctu13_scenario_6
./run_ctu13_scenario_9
./run_ctu13_scenario_13
